version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
